apiVersion: v1
kind: Secret
metadata:
  name: wiki-db-token
  namespace: wiki-db
data:
  username: d2lraWpz
  password: d2lraWpz

---

apiVersion: v1
kind: Secret
metadata:
  name: wiki-wiki-token
  namespace: wiki
data:
  username: d2lraWpz
  password: d2lraWpz