--- 

apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-smtp-token
  namespace: {{ .Release.Namespace }}
data:
  username: dGVjbmljb0BsYXVkZS50ZWNo
  password: QnRuY3hqZGgyZkoxVjA5NA==

---

#Secreto Generado para Hemera-PRO
apiVersion: v1 
kind: Secret
metadata:
  name: hemera-pro-secret-azure
  namespace: {{ .Release.Namespace }}
data:
  id_aplicacion_cliente: MjNmMmQ3YTctODY3Mi00Y2NhLTk4OTUtMDVlZWNkNzY1OTE2
  secret_app_azure_id: ZVBtOFF+LVNoUnV3ZERoMzFxcWVINU8tOXdwLWtyNDRtTzBiSWNrVQ==
  tenant_inquilino_id: NzgzODI2MjgtY2IyNC00NWRjLTkyMzMtMWE0YWRhYTBkN2Uw
