apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: {{ .Release.Namespace }}
  labels:
    app: vaultwarden
spec:
    selector:
      app: vaultwarden
    ports:
      - port: {{ .Values.vaultwarden.port }}
        name: http
        targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: {{ .Release.Namespace }}
  labels:
    app: vaultwarden
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}

    spec:
      securityContext:
        runAsUser: 0

    spec:
      hostname: vaultwarden
      #nodeSelector:
      #  kubernetes.io/hostname: "prok8s-lt"
      containers:
      - image: timshel/oidcwarden:{{ .Values.vaultwarden.imageTag }}
        imagePullPolicy: Always
        name: vaultwarden
        ports:
        - containerPort: 3000
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true

        resources:
          requests:
            memory: "250Mi"
            cpu: "20m"
#          limits:
#            memory: "500Mi"
#            cpu: "500m"

        env:
          - name: TZ
            value: "Europe/Madrid"

          - name: DOMAIN
            value: https://vault.laude.tech


          # Habilita registros de usuarios si lo necesitas
          - name: SIGNUPS_ALLOWED
            value: "true"

          # Websocket para notificaciones en tiempo real
          - name: WEBSOCKET_ENABLED
            value: "true"

          - name: ADMIN_TOKEN
            #value: "sJd8FzP2VYkT+3bX6wPzFmshzU5l8mTkpU1cPqgVRvYzRmHXu4OeQKZjPpLUlQb3"
            value: "$argon2i$v=19$m=16,t=2,p=1$VGRLblNUMTBwWXF0VGdCMQ$xCTtiJm/98BJ0IqDKFWE0A"
            # ===== SMTP (Brevo) =====
          - name: SMTP_HOST
            value: "smtp-relay.brevo.com"
          - name: SMTP_FROM
            value: "tecnico@laude.tech"
          - name: SMTP_FROM_NAME
            value: "Vaultwarden"             
          - name: SMTP_PORT
            value: "587"
          - name: SMTP_SECURITY
            value: "starttls"
          # Opcional pero recomendable con Brevo:
          - name: SMTP_AUTH_MECHANISM
            value: "Login"            

          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: vaultwarden-smtp-token
                key: username                  
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vaultwarden-smtp-token
                key: password

#-----------------------SSO----------------------------------------#            
          - name: SSO_ENABLED
            value: "true"
          - name: SSO_ONLY
            value: "true"
          - name: SSO_AUTHORITY
            value: "https://login.microsoftonline.com/78382628-cb24-45dc-9233-1a4adaa0d7e0/v2.0"
          #- name: SSO_SCOPES
          #  value: "openid profile email"
          - name: SSO_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: hemera-pro-secret-azure
                key: id_aplicacion_cliente
          - name: SSO_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: hemera-pro-secret-azure
                key: secret_app_azure_id


        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 60

        volumeMounts:
          - mountPath: "/data/"
            name: vaultwarden-data


      terminationGracePeriodSeconds: 30

      volumes:
      - name: vaultwarden-data
        hostPath:
          path: /opt/volumes/vaultwarden/data
          type: Directory