#{{ if or (eq .Values.profile "dev") (eq .Values.profile "test") }}
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: proyectos-publicos
#  namespace: {{ .Release.Namespace }}
#  annotations:
#    kubernetes.io/ingress.class: "public"
#    cert-manager.io/cluster-issuer: "letsencrypt-prod"
#    nginx.ingress.kubernetes.io/proxy-body-size: 100m
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#    #{{ if (eq .Values.profile "dev") }}
#    #nginx.ingress.kubernetes.io/whitelist-source-range: "192.148.211.0/24, 90.169.212.155, 88.0.49.108, 88.26.95.9, 79.148.20.84, 66.81.160.84, 81.39.191.236, 81.39.190.78, 213.94.63.133, 213.94.49.91, 212.231.60.68, 88.26.103.108, 79.148.20.118, 79.117.55.96, 66.81.163.84, 213.99.212.102, 139.47.81.181, 82.159.17.7, 86.127.225.194, 213.94.48.36, 88.26.75.50"
#    #{{ else if (eq .Values.profile "test") }}
#    #nginx.ingress.kubernetes.io/whitelist-source-range: "192.148.211.0/24, 90.169.212.155, 88.0.49.108, 88.26.95.9, 79.148.20.84, 66.81.160.84, 81.39.191.236, 81.39.190.78, 213.94.63.133, 213.94.49.91, 212.231.60.68, 88.26.103.108, 79.148.20.118, 79.117.55.96, 66.81.163.84, 213.99.212.102, 139.47.81.181, 82.159.17.7, 86.127.225.194, 213.94.48.36, 88.26.75.50"
#    #{{ end }}
#    #nginx.ingress.kubernetes.io/auth-type: basic
#    #nginx.ingress.kubernetes.io/auth-secret: basic-web-auth
#    #nginx.ingress.kubernetes.io/auth-publicolm: 'Auth OEITS-publico'
#spec:
#  tls:
#  - hosts:
#{{ if (eq .Values.profile "dev") }}
#    - {{ .Values.dev.ingress.host }}
#{{ else if (eq .Values.profile "test") }}
#    - {{ .Values.test.ingress.host }}
#{{ end }}
#    secretName: proyectos-publicos-tls
#  rules:
#{{ if (eq .Values.profile "dev") }}
#  - host: "{{ .Values.dev.ingress.host }}"
#{{ else if (eq .Values.profile "test") }}
#  - host: "{{ .Values.test.ingress.host }}"
#{{ end }}
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: publico-front
#            port:
#              number: {{ .Values.publicofront.port }}                      
#      - path: /api
#        pathType: Prefix
#        backend:
#          service:
#            name: publico-back
#            port:
#              number: {{ .Values.publicoback.port }}
#
### For dev and test
#---
#
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: publico-cloudbeaver
#  namespace: {{ .Release.Namespace }}
#  annotations:
#    kubernetes.io/ingress.class: "public"
#    cert-manager.io/cluster-issuer: "letsencrypt-prod"
#    nginx.ingress.kubernetes.io/proxy-body-size: 100m
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#    #nginx.ingress.kubernetes.io/auth-type: basic
#    #nginx.ingress.kubernetes.io/auth-secret: basic-web-auth
#    #nginx.ingress.kubernetes.io/auth-publicolm: 'Auth OEITS-publico db'
#spec:
#  tls:
#  - hosts:
#{{ if (eq .Values.profile "dev") }}
#    - {{ .Values.dev.ingress.dbhost }}
#{{ else if (eq .Values.profile "test") }}
#    - {{ .Values.test.ingress.dbhost }}
#{{ end }}
#    secretName: proyectos-publicos-db-tls
#  rules:
#{{ if (eq .Values.profile "dev") }}
#  - host: "{{ .Values.dev.ingress.dbhost }}"
#{{ else if (eq .Values.profile "test") }}
#  - host: "{{ .Values.test.ingress.dbhost }}"
#{{ end }}
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: publico-cloudbeaver
#            port:
#              number: {{ .Values.cloudbeaver.port }}
##{{ end }}