{{ if or (eq .Values.profile "dev") (eq .Values.profile "test") }}
apiVersion: v1
kind: Service
metadata:
  name: publico-front
  namespace: {{ .Release.Namespace }}
  labels:
    app: publico-front
spec:
    selector:
      app: publico-front
    ports:
      - port: {{ .Values.publicofront.port }}
        name: http
        targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: publico-front
  namespace: {{ .Release.Namespace }}
  labels:
    app: publico-front
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: publico-front
  template:
    metadata:
      labels:
        app: publico-front
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        
    spec:
      hostname: publico-front
      containers:
      {{ if (eq .Values.profile "dev") }}
      - image: {{ .Values.docker.ns }}/proyectos-publicos-front:dev
      {{ else if (eq .Values.profile "test") }}
      - image: {{ .Values.docker.ns }}/proyectos-publicos-front:test
      {{ end }}
        imagePullPolicy: Always
        name: publico-front
        
        ports:
        - containerPort: 80

        resources:
          requests:
            memory: 100Mi
            cpu: 1m
#          limits:
#            memory: 50Mi
#            cpu: 5m

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 60

      imagePullSecrets:
      - name: publico-docker-registry
{{ end }}
