#Credenciales para bajar imagenes desde nuestro nexus (archivo dockerconfigjson. codificado en base64)
apiVersion: v1
kind: Secret
metadata:
  name: publico-docker-registry
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJhdXRoIjogImJHRjFaR1YwWldOb09tUmphM0pmY0dGMFgwazBlR1F4YkhsV1RWTjVRekoxT0cxSlRXd3lXRnBKVDNwdWR3PT0ifX19
---

apiVersion: v1
kind: Secret
metadata:
  name: publico-db-token
  namespace: {{ .Release.Namespace }}
data:
  username: c2E=
  password: SkBydmlzMjAyMw==

---

apiVersion: v1
kind: Secret
metadata:
  name: basic-web-auth
  namespace: {{ .Release.Namespace }}
data:
  auth: bXRwOiRhcHIxJHd5aTg3MW5wJC5DV002aFBkbEVQYm55V1NmUG1rWi4=